// Export System
// Handles CSV exports, PDF generation, and data export functionality

// Export configuration
const EXPORT_CONFIG = {
  csvDelimiter: ',',
  csvHeaders: true,
  pdfPageSize: 'A4',
  pdfOrientation: 'portrait'
};

// CSV Export Functions
function exportCollectionsToCSV() {
  const collections = getCollectionsData();
  const csvContent = convertToCSV(collections);
  downloadFile(csvContent, 'krishi-collections.csv', 'text/csv');
}

function exportLabReportsToCSV() {
  const labReports = getLabReportsData();
  const csvContent = convertToCSV(labReports);
  downloadFile(csvContent, 'krishi-lab-reports.csv', 'text/csv');
}

function exportProductsToCSV() {
  const products = getProductsData();
  const csvContent = convertToCSV(products);
  downloadFile(csvContent, 'krishi-products.csv', 'text/csv');
}

function exportBlockchainToJSON() {
  const blockchainData = getBlockchainData();
  const jsonContent = JSON.stringify(blockchainData, null, 2);
  downloadFile(jsonContent, 'krishi-blockchain.json', 'application/json');
}

// PDF Export Functions
function exportLabCertificate(testData) {
  try {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    
    // Certificate header
    doc.setFontSize(20);
    doc.setTextColor(45, 106, 79); // Forest green
    doc.text("🌿 KRISHI LAB CERTIFICATE", 105, 20, { align: "center" });
    
    // Certificate details
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Batch ID: ${testData.batchId}`, 20, 40);
    doc.text(`Herb Type: ${testData.herbType}`, 20, 50);
    doc.text(`Farmer: ${testData.farmerName}`, 20, 60);
    doc.text(`Test Result: ${testData.result}`, 20, 70);
    doc.text(`Test Date: ${new Date(testData.timestamp).toLocaleDateString()}`, 20, 80);
    
    // Test parameters
    doc.text("Test Parameters:", 20, 100);
    doc.text(`Moisture: ${testData.parameters.moisture}%`, 30, 110);
    doc.text(`Active Markers: ${testData.parameters.activeMarkers}%`, 30, 120);
    doc.text(`Pesticides: ${testData.parameters.pesticides}`, 30, 130);
    doc.text(`Adulterants: ${testData.parameters.adulterants}`, 30, 140);
    doc.text(`Heavy Metals: ${testData.parameters.heavyMetals}`, 30, 150);
    doc.text(`Microbial Count: ${testData.parameters.microbial}`, 30, 160);
    
    // Lab credentials
    doc.text("Lab Credentials:", 20, 180);
    doc.text("ISO/IEC 17025:2017 Certified", 30, 190);
    doc.text("Lab ID: LAB-001", 30, 200);
    doc.text("Accreditation: National Accreditation Board", 30, 210);
    
    // Blockchain verification
    doc.text("Blockchain Verification:", 20, 230);
    doc.text(`Hash: ${testData.blockHash}`, 30, 240);
    doc.text("Status: Verified on Krishi Blockchain", 30, 250);
    
    // Footer
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Generated by Krishi Platform", 20, 280);
    doc.text(`Date: ${new Date().toLocaleString()}`, 140, 280);
    
    // Save PDF
    doc.save(`Krishi-Certificate-${testData.batchId}.pdf`);
    
    showToast('Lab certificate exported successfully!', 'success');
  } catch (error) {
    console.error('PDF export error:', error);
    showToast('Failed to export PDF certificate', 'error');
  }
}

function exportProductReport(productData) {
  try {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    
    // Report header
    doc.setFontSize(18);
    doc.setTextColor(45, 106, 79);
    doc.text("📦 KRISHI PRODUCT REPORT", 105, 20, { align: "center" });
    
    // Product details
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Product ID: ${productData.productId}`, 20, 40);
    doc.text(`Product Name: ${productData.productName}`, 20, 50);
    doc.text(`Product Type: ${productData.productType}`, 20, 60);
    doc.text(`Batch ID: ${productData.batchId}`, 20, 70);
    doc.text(`Manufacturing Date: ${productData.manufacturingDate}`, 20, 80);
    doc.text(`Expiry Date: ${productData.expiryDate}`, 20, 90);
    
    // Supply chain journey
    doc.text("Supply Chain Journey:", 20, 110);
    doc.text(`1. Herb Collection: ${productData.collectionDate}`, 30, 120);
    doc.text(`2. Lab Testing: ${productData.labTestDate}`, 30, 130);
    doc.text(`3. Manufacturing: ${productData.manufacturingDate}`, 30, 140);
    
    // QR Code information
    doc.text("QR Code Information:", 20, 160);
    doc.text(`QR Code URL: ${window.location.origin}?product=${productData.productId}`, 30, 170);
    doc.text("Scan to view complete supply chain journey", 30, 180);
    
    // Save PDF
    doc.save(`Krishi-Product-Report-${productData.productId}.pdf`);
    
    showToast('Product report exported successfully!', 'success');
  } catch (error) {
    console.error('PDF export error:', error);
    showToast('Failed to export product report', 'error');
  }
}

// Data retrieval functions (would connect to actual data sources)
function getCollectionsData() {
  // Sample data - would be replaced with actual Firestore data
  return [
    { batchId: 'BATCH-001', farmer: 'Ramesh Patel', herb: 'Ashwagandha', quantity: '50kg', date: '2024-03-01', location: '23.25°N, 77.41°E' },
    { batchId: 'BATCH-002', farmer: 'Sita Devi', herb: 'Tulsi', quantity: '30kg', date: '2024-03-02', location: '26.85°N, 80.91°E' }
  ];
}

function getLabReportsData() {
  // Sample data
  return [
    { batchId: 'BATCH-001', herb: 'Ashwagandha', result: 'PASS', moisture: '8.5%', activeMarkers: '1.8%', pesticides: 'None Detected' },
    { batchId: 'BATCH-002', herb: 'Tulsi', result: 'PASS', moisture: '10.2%', activeMarkers: '0.9%', pesticides: 'None Detected' }
  ];
}

function getProductsData() {
  // Sample data
  return [
    { productId: 'PROD-001', name: 'Ashwagandha Premium Extract', type: 'Extract', batchId: 'BATCH-001', mfgDate: '2024-03-05', expiryDate: '2025-03-05' },
    { productId: 'PROD-002', name: 'Tulsi Capsules', type: 'Capsule', batchId: 'BATCH-002', mfgDate: '2024-03-06', expiryDate: '2025-03-06' }
  ];
}

function getBlockchainData() {
  // Sample blockchain data
  return {
    chainName: 'Krishi Herb Traceability',
    chainLength: 10,
    genesisBlock: {
      timestamp: 1709123456789,
      data: { type: 'genesis', message: 'Genesis Block - Krishi Blockchain' },
      hash: '0000000000000000000000000000000000000000000000000000000000000000'
    },
    latestBlock: {
      timestamp: 1709123456789,
      data: { type: 'manufacturing', productId: 'PROD-001' },
      hash: 'a1b2c3d4e5f67890123456789012345678901234567890123456789012345678'
    }
  };
}

// Utility functions
function convertToCSV(data) {
  if (!data || data.length === 0) return '';
  
  const headers = Object.keys(data[0]);
  const csvHeaders = headers.join(EXPORT_CONFIG.csvDelimiter);
  
  const csvRows = data.map(row => {
    return headers.map(header => {
      const value = row[header];
      // Escape commas and quotes in CSV
      if (typeof value === 'string' && (value.includes(',') || value.includes('"'))) {
        return `"${value.replace(/"/g, '""')}"`;
      }
      return value;
    }).join(EXPORT_CONFIG.csvDelimiter);
  });
  
  return EXPORT_CONFIG.csvHeaders ? [csvHeaders, ...csvRows].join('\n') : csvRows.join('\n');
}

function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// Export functions for global use
window.exportSystem = {
  collectionsToCSV: exportCollectionsToCSV,
  labReportsToCSV: exportLabReportsToCSV,
  productsToCSV: exportProductsToCSV,
  blockchainToJSON: exportBlockchainToJSON,
  labCertificate: exportLabCertificate,
  productReport: exportProductReport
};